name: Node.js CI

on:
  push:
    branches: [ '**' ]
  release:
    types: [ published ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: apt update
        run: sudo apt-get update

      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - name: Restore cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{ github.workspace }}/node_modules
          key: node-${{ steps.setup-node.outputs.node-version }}-${{ hashFiles('package-lock.json') }}

      - name: Install build dependencies
        if: steps.cache-restore.outputs.cache-hit != 'true'
        # https://github.com/stackgl/headless-gl?tab=readme-ov-file#ubuntudebian
        # https://github.com/Automattic/node-canvas#compiling
        run: sudo apt-get install -y build-essential libxi-dev libglu1-mesa-dev libglew-dev pkg-config libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - name: Run npm ci
        run: npm ci --build-from-source
        if: steps.cache-restore.outputs.cache-hit != 'true'

      - name: Cache save
        uses: actions/cache/save@v4
        if: steps.cache-restore.outputs.cache-hit != 'true'
        with:
          path: ${{ github.workspace }}/node_modules
          key: node-${{ steps.setup-node.outputs.node-version }}-${{ hashFiles('package-lock.json') }}

      - name: Install xvfb
        run: sudo apt-get install -y xvfb

      - name: Build
        run: npm run build

      - name: Validate Build
        # Why use --auto-servernum: https://stackoverflow.com/a/36002011/10245493
        run: xvfb-run --auto-servernum npm run validate

      - name: Run Unit Tests for @pixi/node
        run: xvfb-run --auto-servernum npm run coverage
        env:
          NODE_ENV: production
